

import React from "react";
export const metadata = {
  title: '这是app router的顶层layout元数据',
  description: 'Generated by Next.js',
}

export default function RootLayout(
  {children,}: { children: React.ReactNode }
) {
  return (
    <html lang="en">
    <body>{children}</body>
    </html>
  )
}
